config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tweets#index"

  get 'all_tweets', to: 'tweets#all'

  resources :tweets do
    resources :comments
  end

  resources :comments do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable

  validates_length_of :body, maximum: 240
  validates :body, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :delete_all

  validates_length_of :body, maximum: 240
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :comments, as: :commentable, through: :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.new comment_params
    if @comment.save
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit
    @comment = Comment.find_by_id(params[:id])
  end

  def update
    @comment = Comment.find_by_id(params[:id])
    if @comment.update(comment_params)
      redirect_to tweets_path
    else
      render "edit"
    end
  end

  def destroy
    @comment = Comment.find_by_id(params[:id])
    @comment.update(body: "**Comment deleted**")
    redirect_to tweets_path
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :user_id)
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Tweet.find_by_id(params[:tweet_id]) if params[:tweet_id]
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!

    def all
      @tweets = Tweet.all
    end

    def index
        @tweets = current_user.tweets
    end

    def new
      @tweet = Tweet.new
    end

    def show
      @tweet = Tweet.find_by(id: params[:id])
    end

    def create
      @tweet = Tweet.create(tweet_params)
      current_user.tweets << @tweet
      if @tweet.save
        redirect_to tweets_path
      else
        render new_tweet_path
      end
    end

    def update
      @tweet = Tweet.find_by_id(params[:id])
      if @tweet.update(tweet_params)
        redirect_to @tweet
      else
        render "edit"
      end
    end

    def edit
      @tweet = Tweet.find_by_id(params[:id])
    end


    def destroy
      @tweet = Tweet.find_by_id(params[:id])
      @tweet.destroy
      redirect_to tweets_path
    end

    private

    def tweet_params
      params.require(:tweet).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="container">
  <li style="list-style: none">
    <div class="row" style="margin: 20px">
      <div class="col">
        <%= comment.body %> -
        <small>Submitted <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user.email %></small>
      </div>
    </div>
      <% if comment.user == current_user  && comment.body != "**Comment deleted**" %>
        <%= link_to "Edit Comment", edit_comment_path(comment), class: "btn btn-primary" %>
        <% if comment.body != "**Comment deleted**" %>
          <%= link_to 'Delete Comment', comment,  method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
        <% end %>
      <% end %>
  <div style="border-bottom: 1px solid grey; padding-bottom: 5px;">
    <% if comment.body != "**Comment deleted**" %>
      <%= form_for [comment, Comment.new] do |f| %>
          <%= f.text_area :body, placeholder: "Add a comment..." %><br/>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.submit "Submit Comment", class: "btn btn-primary" %>
          <% end %>
    <% end %>
  </div>


    <ul style="list-style: none">
        <%= render partial: 'comments/comment', collection: comment.comments %>
    </ul>

  </li>
</div>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= form_for @comment do |f| %>
    <%= f.text_area :body, placeholder: @comment.body %><br/>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "Submit Comment"  %>
    <% end %>

app/views/comments/new.html.erb
<div class="container">
  <div class="row align-items-center justify-content-center">
    <%= form_for @comment, url: {action: "create"} do |f| %>
      <%= render "shared/errors", object: @comment %>
      <%= f.text_area :body %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.submit class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LilTwitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav>
        <ul>
          <li><%= link_to "Lil Twitter", root_path %></li>
          <li><%= link_to "New Tweet", new_tweet_path%></li>
          <li>
            <%= link_to "Global Tweets", all_tweets_path %>
          </li>
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to('Login', new_user_session_path) %>
            </li>
            <% end %>

          </ul>
        </div>
      </nav>
      <div class="row text-center">
        <div class="col">
          <p class="notice"><strong><%= notice %></strong></p>
          <p class="alert"><strong><%= alert %></strong></p>
        </div>
      </div>

      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors %>
  <ul style="list-style: none; color: red">
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/tweets/all.html.erb
<div class="container">
  <ul class="list-group">
    <h1 class="text-center">Global Tweets</h1>
    <% @tweets.each do |tweet| %>
    <div class="row list-group-item">

      <%= link_to tweet.body, tweet_path(tweet), class:"col-md"%>
      <span class="col-md">Author: <%= tweet.user.email %></span>
      <span class="col-md">Submitted: <%= time_ago_in_words(tweet.created_at) %> ago</span>
    </div>
    <% end %>
  </ul>
</div>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>
<div class="row align-items-center justify-content-center">
    <div>
      <%= form_for @tweet, class: "col" do |f| %>
        <%= render "shared/errors", object: @tweet %>
        <%= f.text_field :body, placeholder: @tweet.body %>
        <%= f.submit %>
      <% end %>
    </div>
</div>

app/views/tweets/index.html.erb
<div class="container">
  <h1 class="text-center" style="border-bottom: 1px solid grey">Your Tweets</h1>
  <ul class="list-group">
    <% @tweets.each do |tweet| %>
    <div class="row">
      <div class="col">
        <%= link_to tweet.body, tweet_path(tweet), class:"list-group-item"%>
      </div>
      <div class="row">
        <%= link_to 'Delete Tweet', tweet,  method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
        <%= link_to "Edit Tweet", edit_tweet_path(tweet), class: "btn btn-primary" %>
      </div>
    </div>
    <% end %>
  </ul>
</div>

app/views/tweets/new.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col">
        <h1>Create new tweet</h1>
    </div>

  </div>
  <div class="row">
    <div class="col">
      <div>
        <%= form_for @tweet, class: "col" do |f| %>
          <%= render "shared/errors", object: @tweet %>
          <%= f.text_area :body %>
          <%= f.submit class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>

  </div>
</div>


</div>

app/views/tweets/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-block text-center">
      <p class="card-text" style="padding: 10px"><%= @tweet.body %></p>
      <small class="card-title">Submitted <%= time_ago_in_words(@tweet.created_at) %> ago by <%= @tweet.user.email %></small>
      <div class="row">
        <div class="col text-center">
          <% if @tweet.user == current_user %>
            <%= link_to "Edit Tweet", edit_tweet_path(@tweet), class: "btn btn-primary center-block" %>
            <%= link_to 'Delete Tweet', @tweet,  method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row text-center">
  <div class="col" style="margin-top: 20px">
    <h3>Comments: </h3>
    <%= render(partial: 'comments/comment', collection: @tweet.comments) %>
    <%= link_to "New Comment", new_tweet_comment_path(@tweet), class: "btn btn-primary" %>
  </div>

</div>